### ISSUE TITLE
about Disassemble

### ISSUE THREAD

**Issue by wjh191** [TesterTesterov/ACPXScriptTool#1]
hello！

[Yamizome Revenger](https://vndb.org/v22739

["血色ﾉ悪ｿｳﾅ月が高ｸ昇ｯﾃｲﾙ｡"]
["俺様ﾊビルﾉ屋上ｶﾗｿﾚｦ眺ﾒﾂﾂ､ｿｲﾂが来ﾙﾉｦ<r>待ｯﾃｲﾀ｡"]

The Disassembled content contains non-Japanese text，for example“ﾒﾂﾂ､ｿｲﾂ”，this may be a half-width Katakana

**Comment by wjh191** [comment]
The correct content should be：
血色の悪そうな月が高く昇っている。
俺様はビルの屋上からそれを眺めつつ、そいつが来るのを<r>待っていた。

**Comment by wjh191** [comment]
https://github.com/regomne/chinesize/blob/master/ACPX/extBin.py#L6-L7

**Comment by wjh191** [comment]
When I assemble it（bin_encoding=cp932，txt__encoding=utf16，txt is japanese raw），and an error occurred：[tuple.index(x): x not in tuple]

**Comment by TesterTesterov** [comment]
@wjh191, hello. Well, the engine's scripts contain half-width katakana instead of hiragana. Still, it **is** Japanese text. Just the engine uses this method to make the scripts' sizes smaller, I guess. I can change the representation in the disassembled script, but, again, this is just the internal format and everyone who know enough Japanese can read it.

I'll look into the problem of encoding slightly later.

**Comment by TesterTesterov** [comment]
@wjh191, okay, fixed the representation. I shall add it in the new release after the second problem.
For now, post here the script, with which you had a problem with assembling.

**Comment by wjh191** [comment]
@TesterTesterov
[script.zip](https://github.com/TesterTesterov/ACPXScriptTool/files/10925899/script.zip)

**Comment by TesterTesterov** [comment]
@wjh191, no problem with using UTF-16 was discovered. Perhaps, after my last fix?.. Never mind, I'll just release it as is.

**Comment by TesterTesterov** [comment]
@wjh191, try [1.1 release](https://github.com/TesterTesterov/ACPXScriptTool/releases/tag/1.1). Do note, the bug with UTF-16 may occur if it is not a valid UTF-16-encoding file. So I recommend to use cp932.

**Comment by wjh191** [comment]
yes, assembling is no problem, thank you,  hero.
